apiVersion: v1
data:
  config.yaml: |
    YXBpVmVyc2lvbjogdjFhbHBoYTEKc3BlYzoKICBzeXN0ZW06CiAgICBsb2dMZXZlbDogZG
    VidWcKICAgIHdlYjoKICAgICAgcG9ydDogMzAwMAogICAgICBtZXRyaWNzOiAvbWV0cmlj
    cwoKICAjIFMzIHN0b3JhZ2VzIGNvbmZpZ3VyYXRpb24KICBzdG9yYWdlczoKICAgIC0gbm
    FtZTogczMKICAgICAgczM6CiAgICAgICAgZW5kcG9pbnQ6IG1pbmlvOjkwMDAKICAgICAg
    ICByZWdpb246IHVzLXdlc3QtMQogICAgICAgIGJ1Y2tldDogZGJiYWNrdXBzCiAgICAgIC
    AgYWNjZXNzLWtleTogbWluaW8KICAgICAgICBjbGllbnQtc2VjcmV0OiBtaW5pb3N0b3Jh
    Z2UKICAgIC0gbmFtZTogczMtMgogICAgICBzMzoKICAgICAgICBlbmRwb2ludDogbWluaW
    86OTAwMAogICAgICAgIHJlZ2lvbjogdXMtZWFzdC0xCiAgICAgICAgYnVja2V0OiBkYmJh
    Y2t1cHMKICAgICAgICBhY2Nlc3Mta2V5OiBtaW5pbwogICAgICAgIGNsaWVudC1zZWNyZX
    Q6IG1pbmlvc3RvcmFnZQogICAgLSBuYW1lOiBzMy0zCiAgICAgIHMzOgogICAgICAgIGVu
    ZHBvaW50OiBtaW5pbzo5MDAwCiAgICAgICAgcmVnaW9uOiB1cy1lYXN0LTEKICAgICAgIC
    BidWNrZXQ6IGRiYmFja3VwcwogICAgICAgIGFjY2Vzcy1rZXk6IG1pbmlvCiAgICAgICAg
    Y2xpZW50LXNlY3JldDogbWluaW9zdG9yYWdlCgogICMgRGF0YWJhc2VzIGNvbmZpZ3VyYX
    Rpb24KICBkYXRhYmFzZXM6CiAgICAtIG5hbWU6IHBnCiAgICAgIHR5cGU6IHBvc3RncmVz
    CiAgICAgIGhvc3Q6IHBvc3RncmVzCiAgICAgIHBvcnQ6IDU0MzIKICAgICAgZGI6IHBvc3
    RncmVzCiAgICAgIHVzZXI6IHBvc3RncmVzCiAgICAgIHBhc3N3b3JkOiByb290CiAgICAg
    IG9wdGlvbnM6CiAgICAgICAgLSAtLWluc2VydAogICAgLSBuYW1lOiBwZy0xCiAgICAgIH
    R5cGU6IHBvc3RncmVzCiAgICAgIGhvc3Q6IHBvc3RncmVzCiAgICAgIHBvcnQ6IDU0MzIK
    ICAgICAgZGI6IHBvc3RncmVzCiAgICAgIHVzZXI6IHBvc3RncmVzCiAgICAgIHBhc3N3b3
    JkOiByb290CiAgICAtIG5hbWU6IHBnLTIKICAgICAgdHlwZTogcG9zdGdyZXMKICAgICAg
    aG9zdDogcG9zdGdyZXMKICAgICAgcG9ydDogNTQzMgogICAgICBkYjogcG9zdGdyZXMKIC
    AgICAgdXNlcjogcG9zdGdyZXMKICAgICAgcGFzc3dvcmQ6IHJvb3QKICAgICAgb3B0aW9u
    czoKICAgICAgICAtIC0taW5zZXJ0CgogICMgQ3JvbiBzY2hlZHVsZXMKICBiYWNrdXBzOg
    ogICAgIyBDcm9uIHBhY2thZ2UgdXNlZDogZ2l0aHViLmNvbS9yb2JmaWcvY3JvbgogICAg
    LSBuYW1lOiBwZy1iYWNrdXAtdGFzawogICAgICBzY2hlZHVsZTogIiogKiAqICogKiIKIC
    AgICAgIyBEYXRhYmFzZXMgdG8gYmFja3VwCiAgICAgIGRhdGFiYXNlczoKICAgICAgICAt
    IG5hbWU6IHBnCiAgICAgIHN0b3JhZ2U6CiAgICAgICAgbmFtZTogczMKICAgIC0gbmFtZT
    ogcGctYmFja3VwLXRhc2stMgogICAgICBzY2hlZHVsZTogIiogKiAqICogKiIKICAgICAg
    ZGF0YWJhc2VzOgogICAgICAgIC0gbmFtZTogcGctMQogICAgICBzdG9yYWdlOgogICAgIC
    AgIG5hbWU6IHMzCiAgICAtIG5hbWU6IHBnLWJhY2t1cC10YXNrLTMKICAgICAgc2NoZWR1
    bGU6ICIqLzMgKiAqICogKiIKICAgICAgZGF0YWJhc2VzOgogICAgICAgIC0gbmFtZTogcG
    ctMgogICAgICBzdG9yYWdlOgogICAgICAgIG5hbWU6IHMz
kind: Secret
metadata:
  labels:
    app: backup-controller
  name: backup-controller
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: backup-controller
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: backup-controller
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backup-controller
  name: backup-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup-controller
  template:
    metadata:
      labels:
        app: backup-controller
    spec:
      containers:
      - args:
        - --config
        - /etc/backup-controller/config.yaml
        image: timmiles/backup-controller:latest
        name: backup-controller
        ports:
        - containerPort: 3000
          name: http
        resources: {}
        volumeMounts:
        - mountPath: /etc/backup-controller
          name: secret
      volumes:
      - name: secret
        secret:
          secretName: backup-controller
