apiVersion: backup-controller.ufanet.ru/v1alpha1
spec:
  system:
    logLevel: debug
    web:
      port: 3000

  # Описание storages куда складывать бэкап
  storages:
    - name: local-s3
      s3:
        endpoint: http://127.0.0.1:9000
        region: aaa
        bucket: aaa
        access-key: aaa
        client-secret: aaa
    - name: external-s3
      s3:
        endpoint: http://example.host:9000
        region: bbb
        bucket: bbb
        access-key: bbb
        client-secret: bbb

  # Описание баз данных которые нужно бэкапить
  databases:
    - name: test-pg
      type: postgres
      host: test-pg
      port: 5432
      db: test
      user: $TEST-PG-USER
      password: $TEST-PG-PASSWORD
      options:
        - --insert
    - name: test-pg-2
      type: postgres
      host: test-pg
      db: test
      port: 5432
      user: $TEST-PG-USER
      password: $TEST-PG-PASSWORD
      options:
        - --insert

  # Время когда производить бэкапы
  backups:
    # Крон по спецификации github.com/robfig/cron
    - name: pg-backup-task
      schedule: "0 5 * * *"
      # Базы данных которые нужно бэкапить по этому расписанию
      databases:
        - name: test-pg
        - name: test-pg-2
      storage:
        name: external-s3