version: '3'

services:
  backup-controller:
    build:
      dockerfile: Dockerfile
      context: ../..
    environment:
      PGPASSWORD: root    
    volumes:
      - ./backup-controller:/etc/backup-controller
    command: --config /etc/backup-controller/config.yaml
    # entrypoint: pg_dump
    # command: -v -Fc -f test.sql.tar.gz -d postgres -h postgres -p 5432 -U postgres
  minio:
    image: minio/minio:RELEASE.2021-12-10T23-03-39Z.fips
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniostorage
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address :9001
    volumes:
      - ./minio:/data
  postgres:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080