apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - deployment.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: backup-controller
    files:
      - ./backup-controller/config.yaml
    options:
      labels:
        app: "backup-controller"